# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: develop - Database PR Validation

on:  
  pull_request:
    branches: [ "develop" ]

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      databasechanged: ${{ steps.check.outputs.databasefolder }}
    steps:
      - name: check for changes in database folder
        id: check
        uses: dorny/paths-filter@v2
        with:
          filters: |
           databasefolder: 'sources/ConsoleDatabase/**'
     
  build:
    name: Run PR Build ConsoleDatabase
    runs-on: ubuntu-latest
    needs: check-changes
    if: needs.check-changes.outputs.databasechanged == 'true'    
    env:
      SOLUTION: ./solutions/hbbdemo/hbbdemo.sln
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION }}
    - name: Build
      run: dotnet build ${{ env.SOLUTION }} --configuration Release --no-restore
  
  skip-build:
    runs-on: ubuntu-latest
    needs: check-changes
    if: needs.check-changes.outputs.databasechanged == 'false'
    name: Skip PR Build ConsoleDatabase
    steps:
      - run : echo "no changes in the database project => Build skipped."
